steps:
- name: 'python:3.7'
  args: ['pip3','install', '-r', 'requirements.txt', '-r', 'requirements-test.txt', '--user']

- name: 'python:3.7'
  args: ['python3','-m', 'unittest']

- name: 'python:3.7'
  args: ['./pytype_script.sh']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'roll', '--trigger-http', '--runtime', 'python37', '--entry-point', 'handleHttp']
