steps:
- name: 'python:3.7'
  args: ['pip3','install', '-r', 'requirements.txt', '-r', 'requirements-test.txt', '--user']
- name: 'python:3.7'
  args: ['python3','-m', 'unittest']
- name: 'python:3.7'
  args: ['./pytype_script.sh']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/dice-calculator:$COMMIT_SHA', '.']
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['run', '-d', '--network=cloudbuild', '-e', 'PORT=8080', '-p', '8080:8080', 'gcr.io/$PROJECT_ID/dice-calculator:$COMMIT_SHA']
#- name: 'python:3.7'
#  args: ['sleep','15']
#- name: 'python:3.7'
#  args: ['./locust_script.sh']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/dice-calculator:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
  - 'run'
  - 'deploy'
  - 'dice-calculator'
  - '--image'
  - 'gcr.io/$PROJECT_ID/dice-calculator:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- 'gcr.io/$PROJECT_ID/dice-calculator:$COMMIT_SHA'
