openapi: "3.0.0"
info:
  version: 1.0.0
  title: Dice Calculator
  license:
    name: Affero GPL
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
servers:
  - url: https://dice-calculator.newg.as/v1
paths:
  '/':
    post:
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: './dialogflow.yaml#/components/schemas/GoogleCloudDialogflowV2WebhookRequest'
      responses:
        200:
          description: Response
          content:
            application/json:
              schema:
                $ref: './dialogflow.yaml#/components/schemas/GoogleCloudDialogflowV2WebhookResponse'
        default:
          description: An error occured.
